name: 'Comment Test Coverage'
description: 'Read a Karma Test Coverage coverage-summary.json test report and comment stats on to commit'
inputs:
  token:
    description: 'The GitHub authentication token'
    required: true
  path:
    description: 'Filepath to coverage-summary.json'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-square'  
  color: 'gray-dark'